"""test

Revision ID: bc3fbcdade95
Revises: 8c942cbcf24c
Create Date: 2025-05-29 23:12:43.503101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc3fbcdade95'
down_revision = '8c942cbcf24c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word_pair', sa.Column('cognitive_status', sa.String(length=100), nullable=True))
    op.drop_column('word_pair', 'c_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word_pair', sa.Column('c_status', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('word_pair', 'cognitive_status')
    # ### end Alembic commands ###
